# See https://github.com/idi-ops/ansible-nodejs/blob/master/defaults/main.yml for available variables
# In the Docker build context, this one is our main interest, for building and
# tagging different nodejs versions:
#
# Node.js version required by application (supported versions: 0.10.36*, 0.10.40, 4.2.0, 4.2.1)
nodejs_version: 4.3.0
